export const SIGNUP_USER = 'SIGNUP_USER'
//export const CURRENT_USER = 'CURRENT_USER'
export const LOGIN_USER = 'LOGIN_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const ERROR = 'ERROR'
export const LOADING_CATEGORIES = 'LOADING_CATEGORIES'
export const LOADING_BOOKMARKS = 'LOADING_BOOKMARKS'
export const AUTHENTICATED = 'AUTHENTICATED'

export const CREATE_BOOKMARK = 'CREATE_BOOKMARK'
export const FAVORITE_BOOKMARK = 'FAVORITE_BOOKMARK'
export const EDIT_BOOKMARK = 'EDIT_BOOKMARK'
export const DELETE_BOOKMARK = 'DELETE_BOOKMARK'
export const GET_BOOKMARKS = 'GET_BOOKMARKS'



export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const FILTER_BY_CATEGORY= 'FILTER_BY_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES'
